# Home Assistant Proxmox Monitoring - Sensor Definitions
# This file includes SSH-based sensors for direct hardware monitoring
# Specifically configured for Dell PowerEdge R730XD temperature reading

sensor:
  # R730XD CPU Temperature (via SSH command)
  - platform: command_line
    name: "R730XD CPU Temperature"
    unique_id: "r730xd_cpu_temp"
    command: 'ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 root@192.168.1.10 /usr/local/bin/get-r730xd-temps.sh | grep -oP "\"cpu_temp\": \K[0-9.]+"'
    unit_of_measurement: "°C"
    scan_interval: 30
    value_template: "{{ value | float | round(1) }}"
    device_class: temperature
    icon: "mdi:thermometer"

  # R730XD RAID Temperature (via SSH command)
  - platform: command_line
    name: "R730XD RAID Temperature"
    unique_id: "r730xd_raid_temp"
    command: 'ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 root@192.168.1.10 /usr/local/bin/get-r730xd-temps.sh | grep -oP "\"raid_temp\": \K[0-9.]+"'
    unit_of_measurement: "°C"
    scan_interval: 30
    value_template: "{{ value | float | round(1) }}"
    device_class: temperature
    icon: "mdi:chip"

# ==============================================================================
# CONFIGURATION NOTES
# ==============================================================================
#
# These sensors use SSH command_line platform to query Proxmox directly.
# 
# REQUIREMENTS:
# 1. SSH access from Home Assistant to Proxmox root@192.168.1.10
# 2. Scripts installed on Proxmox:
#    - /usr/local/bin/get-r730xd-temps.sh
#    - /usr/local/bin/ssh-restrict-temps.sh
# 3. Sensors utility installed on Proxmox: apt-get install lm-sensors
#
# SETUP STEPS:
# See QUICKSTART.md or DETAILED_SETUP.md for complete SSH key setup
#
# SSH KEY SETUP:
# 1. Generate key: ssh-keygen -t ed25519 -C "homeassistant@localhost"
# 2. Copy public key to Proxmox: ssh-copy-id -i ~/.ssh/id_ed25519.pub root@192.168.1.10
# 3. Test: ssh root@192.168.1.10 /usr/local/bin/get-r730xd-temps.sh
#
# TROUBLESHOOTING:
# - If "null" values: Check Proxmox script output
# - If connection refused: Verify SSH keys are installed
# - If wrong temp: Run 'sensors' on Proxmox to check sensor names
#
# ==============================================================================
